version: 4.1.0.{build}
os: Visual Studio 2022
environment:
  ASPNETCORE_ENVIRONMENT: appveyor
  COVERALLS_REPO_TOKEN:
    secure: bEnA6TkFDjjP/xdaUY9R5IWCV/dgEUjzRBLOPlRv9aXtBGX87BbtMlvIQlTzEelZ

init:
  - git config --global core.autocrlf input

dotnet_csproj:
  patch: true
  file: 'build\version.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration: Release

build_script:
  - dotnet pack EntityChange.sln --configuration Release --include-symbols --include-source

test_script:
  - dotnet test EntityChange.sln --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*"

artifacts:
- path: artifacts\*.*nupkg
  name: Packages

deploy:
- provider: Environment
  name: MyGet